services:
  svc-gbms-globalsettings:
    container_name: svc-gbms-globalsettings
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    platform: linux/x86_64
    command: sh -c "npm install && npx prisma generate && npm run dev"
    ports:
      - "3009:3000"
    networks:
      - greenn-network
      
networks:
  greenn-network:
    external: true