version: "3"

services:
  fastify:
    build: .
    container_name: fastify-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    env_file:
      - fileName: .env.development

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastify
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
